export type FieldCategory =
  | "Identity"
  | "Blockchain"
  | "Market"
  | "Yield"
  | "Reserve"
  | "Institutional"
  | "Compliance"
  | "Liquidity"
  | "Risk"
  | "Grading"
  | "Source";

export type FieldDefinition = {
  label: string;
  category: FieldCategory;
  shortDescription: string;
  whyItMatters: string;
  example?: string;
  valueType:
    | "string"
    | "number"
    | "boolean"
    | "percentage"
    | "currency"
    | "score"
    | "array"
    | "url"
    | "date"
    | "object";
};

export const FIELD_DEFINITIONS = {
  // Identity layer
  slug: {
    label: "Slug",
    category: "Identity",
    shortDescription: "Stable internal identifier used for the asset in routes, files, and imports.",
    whyItMatters: "Changing a slug can break data imports, URLs, API references, and historical records.",
    example: "franklin-benji, ondo-ousg, superstate-ustb",
    valueType: "string",
  },
  name: {
    label: "Asset Name",
    category: "Identity",
    shortDescription: "The public name of the RWA asset or tokenized product.",
    whyItMatters: "Consistent naming avoids confusion between similarly named products, share classes, wrappers, or protocol tokens.",
    example: "Ondo Short-Term US Government Treasuries",
    valueType: "string",
  },
  symbol: {
    label: "Symbol",
    category: "Identity",
    shortDescription: "The ticker or token symbol used to identify the asset.",
    whyItMatters: "Symbols are not always unique, so they should be checked together with issuer, chain, and contract address.",
    example: "OUSG, USDY, BENJI, USTB",
    valueType: "string",
  },
  fullName: {
    label: "Full Name",
    category: "Identity",
    shortDescription: "The complete legal or product name of the asset when different from its short display name.",
    whyItMatters: "Full names help distinguish the token, fund, protocol, issuer, and share class.",
    example: "Franklin OnChain U.S. Government Money Fund",
    valueType: "string",
  },
  category: {
    label: "Category",
    category: "Identity",
    shortDescription: "The high-level asset class represented by the RWA product.",
    whyItMatters: "Category helps users compare assets with similar risk, yield, liquidity, and regulatory profiles.",
    example: "Treasury, Credit, Real Estate, Commodities",
    valueType: "string",
  },
  subcategory: {
    label: "Subcategory",
    category: "Identity",
    shortDescription: "A more specific classification inside the asset's main category.",
    whyItMatters: "Subcategory improves comparison across assets with different structures inside the same broad RWA category.",
    example: "Tokenized US Treasury Fund, Private Credit Pool, Tokenized Gold",
    valueType: "string",
  },
  description: {
    label: "Description",
    category: "Identity",
    shortDescription: "A factual summary of what the asset is and how it is intended to work.",
    whyItMatters: "A concise description helps users understand the product without relying on marketing language.",
    example: "Tokenized exposure to short-term U.S. Treasury securities.",
    valueType: "string",
  },
  websiteUrl: {
    label: "Website URL",
    category: "Identity",
    shortDescription: "Official website URL for the asset, issuer, or protocol.",
    whyItMatters: "Official websites are usually the first source for issuer identity and product documentation.",
    example: "https://example.com",
    valueType: "url",
  },
  docsUrl: {
    label: "Docs URL",
    category: "Identity",
    shortDescription: "Official documentation URL for the asset or protocol.",
    whyItMatters: "Documentation often contains contract addresses, redemption terms, compliance rules, and technical details.",
    example: "https://docs.example.com",
    valueType: "url",
  },
  twitterUrl: {
    label: "X / Twitter URL",
    category: "Identity",
    shortDescription: "Official social account URL for the issuer, protocol, or asset.",
    whyItMatters: "Social sources can support discovery, but should not replace official docs for production data.",
    example: "https://x.com/example",
    valueType: "url",
  },
  launchDate: {
    label: "Launch Date",
    category: "Identity",
    shortDescription: "The date the asset, fund, or tokenized product launched, when verifiable.",
    whyItMatters: "Launch date helps measure operating history and maturity.",
    example: "2023-01-10",
    valueType: "date",
  },
  isin: {
    label: "ISIN",
    category: "Identity",
    shortDescription: "International Securities Identification Number, if the underlying or tokenized product has one.",
    whyItMatters: "ISIN can link tokenized products to traditional securities infrastructure and regulated fund records.",
    example: "US1234567890",
    valueType: "string",
  },
  tags: {
    label: "Tags",
    category: "Identity",
    shortDescription: "Structured labels describing key asset traits.",
    whyItMatters: "Tags make filtering and search easier across the dataset.",
    example: "institutional, kyc-required, sec-registered, cross-chain",
    valueType: "array",
  },

  // Blockchain layer
  chain: {
    label: "Chain",
    category: "Blockchain",
    shortDescription: "Blockchain network where the asset token or contract is deployed.",
    whyItMatters: "Chain selection affects custody, settlement, fees, integrations, and technical risk.",
    example: "Ethereum, Polygon, Stellar, Solana, Base",
    valueType: "string",
  },
  chainId: {
    label: "Chain ID",
    category: "Blockchain",
    shortDescription: "Numeric identifier for an EVM-compatible blockchain network.",
    whyItMatters: "Chain ID helps prevent confusion between similarly named networks or contract deployments.",
    example: "1 for Ethereum mainnet, 8453 for Base",
    valueType: "number",
  },
  contractAddress: {
    label: "Contract Address",
    category: "Blockchain",
    shortDescription: "On-chain smart contract address for the token or related asset contract.",
    whyItMatters: "Incorrect contract addresses can cause users and systems to track the wrong token.",
    example: "0x...",
    valueType: "string",
  },
  tokenStandard: {
    label: "Token Standard",
    category: "Blockchain",
    shortDescription: "Technical token standard used by the asset contract.",
    whyItMatters: "Token standards affect wallet support, transfers, compliance hooks, and DeFi integrations.",
    example: "ERC-20, ERC-1404, SPL, Stellar asset",
    valueType: "string",
  },
  isTransferable: {
    label: "Transferable",
    category: "Blockchain",
    shortDescription: "Indicates whether the token can be transferred between wallets.",
    whyItMatters: "Transferability is a core liquidity and composability factor for tokenized assets.",
    example: "false for non-transferable or restricted fund shares",
    valueType: "boolean",
  },
  hasWhitelist: {
    label: "Whitelist Enabled",
    category: "Blockchain",
    shortDescription: "Indicates whether token transfers or holdings depend on a whitelist.",
    whyItMatters: "Whitelists support compliance but can limit secondary-market participation.",
    example: "true when only approved wallets can hold or receive the token",
    valueType: "boolean",
  },
  hasTransferRestrictions: {
    label: "Transfer Restrictions",
    category: "Blockchain",
    shortDescription: "Shows whether smart-contract or issuer rules restrict token transfers.",
    whyItMatters: "Transfer restrictions can materially affect liquidity, settlement, and composability.",
    example: "jurisdiction, whitelist, KYC, or lock-up restrictions",
    valueType: "boolean",
  },
  explorerUrl: {
    label: "Explorer URL",
    category: "Blockchain",
    shortDescription: "Blockchain explorer URL for the contract or token.",
    whyItMatters: "Explorer links help verify contract deployment, holders, transactions, and source-code status.",
    example: "https://etherscan.io/token/0x...",
    valueType: "url",
  },
  deployedAt: {
    label: "Deployed At",
    category: "Blockchain",
    shortDescription: "Date or timestamp when the contract was deployed, if known.",
    whyItMatters: "Deployment age helps evaluate operating history and upgrade timeline.",
    example: "2024-03-15",
    valueType: "date",
  },
  isVerified: {
    label: "Verified Contract",
    category: "Blockchain",
    shortDescription: "Indicates whether the contract source code or deployment is verified on a reliable explorer.",
    whyItMatters: "Verified contracts improve transparency for technical review, but do not replace audits.",
    example: "true on Etherscan verified source code",
    valueType: "boolean",
  },

  // Market layer
  tvl: {
    label: "TVL",
    category: "Market",
    shortDescription: "Total value locked or tracked value associated with the asset or protocol.",
    whyItMatters: "TVL can indicate market adoption, but it should be verified against official AUM, issuer reports, or reliable data aggregators.",
    example: "$892.4M",
    valueType: "currency",
  },
  tvl7dChange: {
    label: "TVL 7D Change",
    category: "Market",
    shortDescription: "Percentage change in TVL over the last seven days.",
    whyItMatters: "Short-term TVL movement can show inflows, outflows, or data volatility, but should not be treated as standalone risk evidence.",
    example: "+3.2% over 7 days",
    valueType: "percentage",
  },
  tvl30dChange: {
    label: "TVL 30D Change",
    category: "Market",
    shortDescription: "Percentage change in TVL over the last thirty days.",
    whyItMatters: "Thirty-day change provides a more stable view of adoption or outflow trends than daily movement.",
    example: "+12.4% over 30 days",
    valueType: "percentage",
  },
  change7d: {
    label: "7D Change",
    category: "Market",
    shortDescription: "The asset's observed change over the last seven days.",
    whyItMatters: "Seven-day change helps users quickly understand short-term market movement, but it should not be treated as a long-term risk signal.",
    example: "+3.2% over 7 days",
    valueType: "percentage",
  },
  price: {
    label: "Price",
    category: "Market",
    shortDescription: "Latest available asset or token price.",
    whyItMatters: "Price data must be interpreted carefully for RWAs because some assets are NAV-based, permissioned, or thinly traded.",
    example: "$1.00 or $100.25 NAV",
    valueType: "currency",
  },
  priceChange24h: {
    label: "24H Price Change",
    category: "Market",
    shortDescription: "Percentage change in token price over the last 24 hours.",
    whyItMatters: "Short-term price movement may reflect trading activity, oracle updates, or secondary-market noise.",
    example: "+0.18%",
    valueType: "percentage",
  },
  marketCap: {
    label: "Market Cap",
    category: "Market",
    shortDescription: "Estimated circulating value of the token or asset in the market.",
    whyItMatters: "Market cap can help compare asset scale, but it may be unreliable if supply, pricing, or transferability is unclear.",
    example: "circulatingSupply × price",
    valueType: "currency",
  },
  volume24h: {
    label: "24H Volume",
    category: "Market",
    shortDescription: "Trading volume observed over the last 24 hours.",
    whyItMatters: "Higher volume may indicate better secondary-market liquidity, but issuer redemption terms can be more important for permissioned RWAs.",
    example: "$1.2M traded in 24 hours",
    valueType: "currency",
  },
  circulatingSupply: {
    label: "Circulating Supply",
    category: "Market",
    shortDescription: "Number of tokens currently circulating or available in the market.",
    whyItMatters: "Supply figures affect market cap, holder concentration, and adoption metrics.",
    example: "10,000,000 tokens",
    valueType: "number",
  },
  totalSupply: {
    label: "Total Supply",
    category: "Market",
    shortDescription: "Total number of tokens minted or recorded by the contract or issuer.",
    whyItMatters: "Total supply helps reconcile token issuance with reserves, AUM, and circulating supply.",
    example: "12,000,000 tokens",
    valueType: "number",
  },
  holderCount: {
    label: "Holder Count",
    category: "Market",
    shortDescription: "Number of wallets or accounts holding the token.",
    whyItMatters: "Holder count helps estimate adoption and concentration risk, but wallet counts can be distorted by custodians or internal treasury wallets.",
    example: "1,240 holders",
    valueType: "number",
  },
  holderChange7d: {
    label: "Holder 7D Change",
    category: "Market",
    shortDescription: "Change in token holder count over the last seven days.",
    whyItMatters: "Holder growth can indicate adoption, but must be interpreted carefully for permissioned or custodial assets.",
    example: "+32 holders",
    valueType: "number",
  },
  aumUsd: {
    label: "AUM",
    category: "Market",
    shortDescription: "Assets under management reported in U.S. dollars.",
    whyItMatters: "AUM is often more relevant than secondary-market TVL for regulated funds and tokenized treasury products.",
    example: "$500M AUM from issuer disclosure",
    valueType: "currency",
  },
  lastUpdated: {
    label: "Last Updated",
    category: "Source",
    shortDescription: "Date or timestamp when the field or dataset was last updated.",
    whyItMatters: "Stale data can mislead users, especially for market, yield, reserve, and regulatory fields.",
    example: "2026-06-04",
    valueType: "date",
  },

  // Yield layer
  currentYield: {
    label: "Current Yield",
    category: "Yield",
    shortDescription: "The latest available yield or APY reported for the asset.",
    whyItMatters: "Yield should be tied to a verifiable source and methodology because RWA products may report net yield, gross yield, APY, or benchmark-linked rates differently.",
    example: "5.42% APY",
    valueType: "percentage",
  },
  yieldType: {
    label: "Yield Type",
    category: "Yield",
    shortDescription: "The method used to describe the asset return, such as APY, distribution yield, or target yield.",
    whyItMatters: "Different yield types are not directly comparable without understanding fees, compounding, and distribution mechanics.",
    example: "APY, net yield, target yield, distribution yield",
    valueType: "string",
  },
  yieldFrequency: {
    label: "Yield Frequency",
    category: "Yield",
    shortDescription: "How often yield is accrued, distributed, rebased, or reported.",
    whyItMatters: "Frequency affects user expectations about cash flow, compounding, and reporting cadence.",
    example: "daily, monthly, quarterly, variable",
    valueType: "string",
  },
  yieldBenchmark: {
    label: "Yield Benchmark",
    category: "Yield",
    shortDescription: "Reference benchmark used to compare the asset yield.",
    whyItMatters: "Benchmarks help users evaluate whether the yield is attractive relative to comparable low-risk or market rates.",
    example: "SOFR, 3M T-bill, Fed Funds, USDC lending rate",
    valueType: "string",
  },
  yieldVsBenchmark: {
    label: "Yield vs Benchmark",
    category: "Yield",
    shortDescription: "Difference between the asset yield and its relevant benchmark.",
    whyItMatters: "A spread over benchmark may reflect risk premium, fees, leverage, or methodology differences.",
    example: "+0.35% over 3M T-bill",
    valueType: "percentage",
  },
  yieldAvg7d: {
    label: "7D Average Yield",
    category: "Yield",
    shortDescription: "Average observed yield over the last seven days.",
    whyItMatters: "Short-term averages smooth daily volatility but may still be sensitive to reporting changes.",
    example: "5.31%",
    valueType: "percentage",
  },
  yieldAvg30d: {
    label: "30D Average Yield",
    category: "Yield",
    shortDescription: "Average observed yield over the last thirty days.",
    whyItMatters: "Thirty-day averages help compare assets with changing rates or variable APYs.",
    example: "5.28%",
    valueType: "percentage",
  },
  yieldAvg90d: {
    label: "90D Average Yield",
    category: "Yield",
    shortDescription: "Average observed yield over the last ninety days.",
    whyItMatters: "Longer yield averages provide better context for trend and stability analysis.",
    example: "5.12%",
    valueType: "percentage",
  },
  yieldMin52w: {
    label: "52W Minimum Yield",
    category: "Yield",
    shortDescription: "Lowest observed yield over the last 52 weeks.",
    whyItMatters: "The 52-week minimum helps assess downside variability in yield.",
    example: "4.72%",
    valueType: "percentage",
  },
  yieldMax52w: {
    label: "52W Maximum Yield",
    category: "Yield",
    shortDescription: "Highest observed yield over the last 52 weeks.",
    whyItMatters: "The 52-week maximum helps users understand historical upper range and rate sensitivity.",
    example: "5.83%",
    valueType: "percentage",
  },
  yieldStdDev30d: {
    label: "30D Yield Volatility",
    category: "Yield",
    shortDescription: "Standard deviation of yield over the last thirty days.",
    whyItMatters: "Yield volatility helps identify unstable or frequently changing return profiles.",
    example: "0.08% standard deviation",
    valueType: "percentage",
  },
  nextYieldDate: {
    label: "Next Yield Date",
    category: "Yield",
    shortDescription: "Next expected date for yield accrual, distribution, rebasing, or reporting.",
    whyItMatters: "This helps users understand timing of distributions or updates.",
    example: "2026-06-30",
    valueType: "date",
  },
  yieldCurrency: {
    label: "Yield Currency",
    category: "Yield",
    shortDescription: "Currency or asset in which yield is paid or denominated.",
    whyItMatters: "Yield currency affects FX exposure, settlement, and reinvestment assumptions.",
    example: "USD, USDC, token shares",
    valueType: "string",
  },

  // Reserve layer
  backingType: {
    label: "Backing Type",
    category: "Reserve",
    shortDescription: "The underlying real-world asset or collateral type backing the token.",
    whyItMatters: "Backing type is central to understanding credit risk, duration risk, liquidity risk, and regulatory treatment.",
    example: "US Treasury, Money Market Fund, Private Credit, Commodity",
    valueType: "string",
  },
  backingDescription: {
    label: "Backing Description",
    category: "Reserve",
    shortDescription: "Short explanation of what backs the asset and how the backing is structured.",
    whyItMatters: "Backing descriptions help avoid oversimplifying complex reserve, collateral, or fund structures.",
    example: "Short-term U.S. Treasuries and cash equivalents held by the fund.",
    valueType: "string",
  },
  collateralizationRatio: {
    label: "Collateralization Ratio",
    category: "Reserve",
    shortDescription: "The ratio between backing assets and token liabilities, when explicitly disclosed.",
    whyItMatters: "A verified collateralization ratio can reduce backing uncertainty, but it should not be estimated without a source.",
    example: "1.0 means 100% collateralized",
    valueType: "number",
  },
  custodian: {
    label: "Custodian",
    category: "Reserve",
    shortDescription: "The institution responsible for safekeeping cash, securities, commodities, or other backing assets.",
    whyItMatters: "A credible custodian can reduce operational and asset-safekeeping risk.",
    example: "Bank, qualified custodian, transfer agent, or regulated financial institution",
    valueType: "string",
  },
  custodianUrl: {
    label: "Custodian URL",
    category: "Reserve",
    shortDescription: "Source URL supporting the custodian relationship or custody disclosure.",
    whyItMatters: "Custody claims should be supported by issuer, fund, or custodian documentation.",
    example: "Official fund document or custodian disclosure URL",
    valueType: "url",
  },
  hasProofOfReserves: {
    label: "Proof of Reserves",
    category: "Reserve",
    shortDescription: "Indicates whether public evidence of backing or reserves is available.",
    whyItMatters: "Proof of reserves may reduce transparency risk, but it must be distinguished from smart-contract audits or marketing claims.",
    example: "Attestation report, fund report, custodian report, or on-chain reserve oracle",
    valueType: "boolean",
  },
  porOracleAddress: {
    label: "PoR Oracle Address",
    category: "Reserve",
    shortDescription: "On-chain oracle address used for proof-of-reserves data, if available.",
    whyItMatters: "A verifiable oracle can improve reserve transparency, but only if the oracle methodology is reliable.",
    example: "0x...",
    valueType: "string",
  },
  porOracleChain: {
    label: "PoR Oracle Chain",
    category: "Reserve",
    shortDescription: "Blockchain network where the proof-of-reserves oracle is deployed.",
    whyItMatters: "Oracle chain context is needed to verify address, data freshness, and integrations.",
    example: "Ethereum, Polygon, Base",
    valueType: "string",
  },
  auditor: {
    label: "Auditor",
    category: "Reserve",
    shortDescription: "The auditor or attestation provider associated with the asset, fund, or reserve report.",
    whyItMatters: "Independent audit or attestation can improve confidence in reported backing, fund operations, and controls.",
    example: "Independent audit firm or attestation provider",
    valueType: "string",
  },
  lastAuditDate: {
    label: "Last Audit Date",
    category: "Reserve",
    shortDescription: "Date of the latest audit, attestation, or reserve report relevant to the backing.",
    whyItMatters: "Recent reports are more useful for reserve confidence than stale disclosures.",
    example: "2026-05-31",
    valueType: "date",
  },
  lastAuditUrl: {
    label: "Last Audit URL",
    category: "Reserve",
    shortDescription: "URL to the latest relevant audit, attestation, fund report, or reserve report.",
    whyItMatters: "Audit claims must point to a verifiable document, not just general marketing language.",
    example: "https://issuer.com/reports/latest.pdf",
    valueType: "url",
  },
  reserveBreakdown: {
    label: "Reserve Breakdown",
    category: "Reserve",
    shortDescription: "Breakdown of reserve or collateral components when disclosed.",
    whyItMatters: "Reserve composition affects duration risk, credit risk, liquidity risk, and concentration.",
    example: "Treasuries 80%, cash 20%",
    valueType: "object",
  },
  redemptionAsset: {
    label: "Redemption Asset",
    category: "Reserve",
    shortDescription: "Asset, currency, or instrument received when redeeming the token.",
    whyItMatters: "Redemption asset determines settlement exposure and user expectations at exit.",
    example: "USD, USDC, underlying fund shares, gold",
    valueType: "string",
  },

  // Institutional layer
  issuerName: {
    label: "Issuer Name",
    category: "Institutional",
    shortDescription: "Legal entity or organization issuing the asset or tokenized product.",
    whyItMatters: "Issuer clarity is essential for accountability, legal analysis, and institutional due diligence.",
    example: "Franklin Templeton, Ondo Finance, Superstate",
    valueType: "string",
  },
  issuerCountry: {
    label: "Issuer Country",
    category: "Institutional",
    shortDescription: "Primary jurisdiction of the issuer or issuing entity.",
    whyItMatters: "Issuer jurisdiction affects regulatory framework, investor eligibility, and legal risk.",
    example: "United States, British Virgin Islands, Singapore",
    valueType: "string",
  },
  legalStructure: {
    label: "Legal Structure",
    category: "Institutional",
    shortDescription: "Legal form of the product or issuing vehicle.",
    whyItMatters: "Legal structure determines investor rights, claims on assets, and regulatory obligations.",
    example: "registered fund, SPV, trust, tokenized note, limited partnership",
    valueType: "string",
  },
  fundManager: {
    label: "Fund Manager",
    category: "Institutional",
    shortDescription: "Entity responsible for managing the fund or asset strategy.",
    whyItMatters: "Manager quality and regulation are important for operational and fiduciary risk.",
    example: "Registered investment adviser or asset manager",
    valueType: "string",
  },
  transferAgent: {
    label: "Transfer Agent",
    category: "Institutional",
    shortDescription: "Entity responsible for maintaining ownership records or fund share registry.",
    whyItMatters: "Transfer agents are important for regulated fund administration and investor recordkeeping.",
    example: "Registered transfer agent",
    valueType: "string",
  },
  administrator: {
    label: "Administrator",
    category: "Institutional",
    shortDescription: "Fund or asset administrator responsible for operations, reporting, or NAV processes.",
    whyItMatters: "Administrators can improve operational controls and reporting quality.",
    example: "Fund administrator or third-party operations provider",
    valueType: "string",
  },
  attestationProvider: {
    label: "Attestation Provider",
    category: "Institutional",
    shortDescription: "Entity providing attestations about reserves, fund assets, controls, or other disclosures.",
    whyItMatters: "Attestation providers support confidence in reported data when full audits are not available.",
    example: "Accounting firm or independent attestation provider",
    valueType: "string",
  },
  minimumInvestment: {
    label: "Minimum Investment",
    category: "Institutional",
    shortDescription: "Minimum amount required to subscribe, mint, or invest in the product.",
    whyItMatters: "Minimum investment helps identify target investor segment and accessibility.",
    example: "$100,000 minimum subscription",
    valueType: "currency",
  },
  managementFee: {
    label: "Management Fee",
    category: "Institutional",
    shortDescription: "Ongoing fee charged by the manager or issuer, if disclosed.",
    whyItMatters: "Fees affect net yield and comparability across products.",
    example: "0.15% per year",
    valueType: "percentage",
  },
  performanceFee: {
    label: "Performance Fee",
    category: "Institutional",
    shortDescription: "Fee charged based on investment performance, if applicable.",
    whyItMatters: "Performance fees can materially affect net returns and incentives.",
    example: "10% of returns above hurdle rate",
    valueType: "percentage",
  },
  targetInvestors: {
    label: "Target Investors",
    category: "Institutional",
    shortDescription: "Intended investor group for the asset.",
    whyItMatters: "Target investor information helps assess suitability, compliance requirements, and access restrictions.",
    example: "institutional, accredited, qualified purchaser, retail",
    valueType: "array",
  },

  // Compliance layer
  kycRequired: {
    label: "KYC Required",
    category: "Compliance",
    shortDescription: "Shows whether users must complete identity verification before accessing, minting, redeeming, or transferring the asset.",
    whyItMatters: "KYC can improve regulatory control but may reduce permissionless access and composability.",
    example: "true when issuer requires verified investor onboarding",
    valueType: "boolean",
  },
  accreditedOnly: {
    label: "Accredited Only",
    category: "Compliance",
    shortDescription: "Indicates whether the asset is limited to accredited, qualified, or professional investors.",
    whyItMatters: "Investor eligibility restrictions affect who can legally access the asset and how it can be distributed.",
    example: "true for products limited to qualified purchasers or accredited investors",
    valueType: "boolean",
  },
  transferRestricted: {
    label: "Transfer Restricted",
    category: "Compliance",
    shortDescription: "Shows whether token transfers are restricted by whitelist, jurisdiction, eligibility, or compliance rules.",
    whyItMatters: "Transfer restrictions may improve compliance but can reduce liquidity and DeFi composability.",
    example: "Only whitelisted wallets can receive the token",
    valueType: "boolean",
  },
  sanctionsScreening: {
    label: "Sanctions Screening",
    category: "Compliance",
    shortDescription: "Indicates whether users, wallets, or transactions are screened against sanctions restrictions.",
    whyItMatters: "Sanctions controls are important for institutional adoption and regulatory risk management.",
    example: "OFAC or equivalent screening process disclosed by issuer",
    valueType: "boolean",
  },
  regulatoryStatus: {
    label: "Regulatory Status",
    category: "Compliance",
    shortDescription: "The disclosed regulatory posture of the issuer, fund, token, or offering.",
    whyItMatters: "Regulatory status helps users understand whether the product is registered, exempt, restricted, or unclear.",
    example: "registered, exempt, private offering, regulated fund",
    valueType: "string",
  },
  primaryRegulator: {
    label: "Primary Regulator",
    category: "Compliance",
    shortDescription: "Main regulator associated with the issuer, fund, offering, or product.",
    whyItMatters: "Regulator visibility strengthens institutional due diligence and legal traceability.",
    example: "SEC, CFTC, FINMA, MAS",
    valueType: "string",
  },
  regulatoryFramework: {
    label: "Regulatory Framework",
    category: "Compliance",
    shortDescription: "Legal or regulatory framework under which the asset is offered or operated.",
    whyItMatters: "Framework clarifies investor eligibility, disclosures, restrictions, and compliance obligations.",
    example: "Reg D, Reg S, Investment Company Act, MiCA",
    valueType: "string",
  },
  prospectusUrl: {
    label: "Prospectus URL",
    category: "Compliance",
    shortDescription: "URL to the prospectus, offering memorandum, or equivalent product document.",
    whyItMatters: "Prospectus or offering documents are key sources for legal structure, fees, risks, and investor rights.",
    example: "SEC filing or issuer-hosted prospectus PDF",
    valueType: "url",
  },
  legalOpinionUrl: {
    label: "Legal Opinion URL",
    category: "Compliance",
    shortDescription: "URL to a legal opinion or legal analysis document, if publicly available.",
    whyItMatters: "Legal opinions can support claims around token status, enforceability, or regulatory treatment.",
    example: "Public legal memo or counsel opinion URL",
    valueType: "url",
  },
  blockedJurisdictions: {
    label: "Blocked Jurisdictions",
    category: "Compliance",
    shortDescription: "Jurisdictions where the asset is not offered or users are restricted.",
    whyItMatters: "Jurisdiction restrictions affect distribution, compliance risk, and user access.",
    example: "US persons blocked, sanctioned countries blocked",
    valueType: "array",
  },
  allowedJurisdictions: {
    label: "Allowed Jurisdictions",
    category: "Compliance",
    shortDescription: "Jurisdictions where eligible users may access the asset, if disclosed.",
    whyItMatters: "Allowed jurisdictions clarify the product's intended regulatory perimeter.",
    example: "Qualified non-US investors, selected EEA jurisdictions",
    valueType: "array",
  },
  amlPolicy: {
    label: "AML Policy",
    category: "Compliance",
    shortDescription: "Anti-money laundering controls or policy references disclosed by the issuer.",
    whyItMatters: "AML controls are important for institutional adoption and regulated distribution.",
    example: "Issuer onboarding includes AML screening and monitoring",
    valueType: "string",
  },

  // Liquidity layer
  redemptionType: {
    label: "Redemption Type",
    category: "Liquidity",
    shortDescription: "The mechanism used to redeem the token into cash, stablecoin, or the underlying asset.",
    whyItMatters: "Issuer-supported redemption can matter more than DEX liquidity for many permissioned RWA assets.",
    example: "instant, T+1, T+3, weekly, monthly, gated",
    valueType: "string",
  },
  redemptionPeriodDays: {
    label: "Redemption Period",
    category: "Liquidity",
    shortDescription: "Estimated number of days required to redeem the asset after a valid redemption request.",
    whyItMatters: "Longer redemption periods increase exit risk, especially during market stress or operational disruptions.",
    example: "1 means approximately T+1 business day",
    valueType: "number",
  },
  lockupPeriodDays: {
    label: "Lock-up Period",
    category: "Liquidity",
    shortDescription: "The period during which holders may be unable to redeem or transfer the asset.",
    whyItMatters: "Lock-ups can materially reduce liquidity even when the underlying asset is high quality.",
    example: "30 days lock-up after subscription",
    valueType: "number",
  },
  earlyRedemptionFee: {
    label: "Early Redemption Fee",
    category: "Liquidity",
    shortDescription: "Fee charged when redeeming before a specified period or condition.",
    whyItMatters: "Early redemption fees can reduce effective liquidity and realized returns.",
    example: "1.0% early exit fee",
    valueType: "percentage",
  },
  minRedemptionAmount: {
    label: "Minimum Redemption Amount",
    category: "Liquidity",
    shortDescription: "Minimum amount required to redeem the asset.",
    whyItMatters: "High minimum redemption amounts can limit smaller holders' exit options.",
    example: "$10,000 minimum redemption",
    valueType: "currency",
  },
  dexPairs: {
    label: "DEX Pairs",
    category: "Liquidity",
    shortDescription: "Known decentralized exchange pools or trading pairs for the token.",
    whyItMatters: "DEX pairs can provide secondary liquidity, but pool depth and permissions must be verified.",
    example: "TOKEN/USDC on Uniswap",
    valueType: "array",
  },
  onchainLiquidity: {
    label: "On-chain Liquidity",
    category: "Liquidity",
    shortDescription: "Available liquidity visible on DEXs, pools, or other on-chain markets.",
    whyItMatters: "On-chain liquidity affects secondary-market exits, but may be less relevant for assets primarily redeemed with the issuer.",
    example: "$250K available across verified pools",
    valueType: "currency",
  },
  bidAskSpread: {
    label: "Bid-Ask Spread",
    category: "Liquidity",
    shortDescription: "Difference between best available buy and sell prices, when observable.",
    whyItMatters: "Wider spreads indicate higher trading cost and weaker secondary-market liquidity.",
    example: "0.25% spread",
    valueType: "percentage",
  },
  liquidityScore: {
    label: "Liquidity Score",
    category: "Liquidity",
    shortDescription: "A score estimating how easily the asset can be bought, sold, transferred, or redeemed.",
    whyItMatters: "Lower liquidity scores may indicate delayed redemption, transfer restrictions, limited market depth, or high exit uncertainty.",
    example: "85-100 for instant redemption; lower for longer windows or lock-ups",
    valueType: "score",
  },
  liquidityNotes: {
    label: "Liquidity Notes",
    category: "Liquidity",
    shortDescription: "Analyst notes explaining liquidity constraints, assumptions, or unresolved questions.",
    whyItMatters: "Narrative notes can explain why liquidity scores differ from simple redemption timing.",
    example: "Issuer redemption available, but secondary DEX liquidity is limited.",
    valueType: "string",
  },

  // Risk and grading layer
  smartContractRisk: {
    label: "Smart Contract Risk",
    category: "Risk",
    shortDescription: "Risk related to contract code, audits, upgrades, permissions, or exploit history.",
    whyItMatters: "Smart-contract weaknesses can affect token safety even when underlying assets are high quality.",
    example: "High if contract is unverified or unaudited",
    valueType: "score",
  },
  marketRisk: {
    label: "Market Risk",
    category: "Risk",
    shortDescription: "Risk related to adoption, trading activity, TVL stability, price behavior, or market depth.",
    whyItMatters: "Market risk helps distinguish mature assets from thinly traded or low-adoption products.",
    example: "Higher risk when volume, holders, and liquidity are low",
    valueType: "score",
  },
  concentrationRisk: {
    label: "Concentration Risk",
    category: "Risk",
    shortDescription: "Risk arising from concentrated ownership, collateral, counterparties, or liquidity sources.",
    whyItMatters: "Concentration can increase vulnerability to a small number of holders, issuers, or counterparties.",
    example: "High if top wallets hold most of supply",
    valueType: "score",
  },
  legalRisk: {
    label: "Legal Risk",
    category: "Risk",
    shortDescription: "Risk related to unclear legal structure, investor rights, regulator status, or jurisdiction exposure.",
    whyItMatters: "Legal uncertainty can block institutional adoption even when market data looks strong.",
    example: "High when issuer and offering docs are unclear",
    valueType: "score",
  },
  riskScore: {
    label: "Risk Score",
    category: "Risk",
    shortDescription: "Composite score summarizing the asset's observed risk profile based on available data.",
    whyItMatters: "Risk score helps compare assets, but it is a data-quality and risk indicator, not investment advice.",
    example: "88 out of 100",
    valueType: "score",
  },
  blockers: {
    label: "Blockers",
    category: "Grading",
    shortDescription: "Critical issues preventing an asset from reaching a higher data quality grade.",
    whyItMatters: "Blockers make limitations explicit instead of hiding unresolved risks behind a single score.",
    example: "Unverified contract address, missing reserve source",
    valueType: "array",
  },
  warnings: {
    label: "Warnings",
    category: "Grading",
    shortDescription: "Important but non-blocking issues users should notice.",
    whyItMatters: "Warnings improve transparency for incomplete, stale, or lower-confidence data.",
    example: "No public legal opinion found",
    valueType: "array",
  },
  legalScore: {
    label: "Legal Score",
    category: "Grading",
    shortDescription: "Score reflecting legal documentation, issuer clarity, regulator visibility, and investor eligibility disclosures.",
    whyItMatters: "Legal opacity can be a blocker for institutional-grade classification.",
    example: "Higher when prospectus, offering docs, regulator records, and terms are publicly verifiable",
    valueType: "score",
  },
  reserveScore: {
    label: "Reserve Score",
    category: "Grading",
    shortDescription: "Score reflecting the quality and verifiability of asset backing, reserve reporting, custody, and audits.",
    whyItMatters: "Reserve transparency is critical for determining whether an RWA token is credibly backed.",
    example: "Higher when backing, custodian, and audit/attestation sources are strong",
    valueType: "score",
  },
  sourceScore: {
    label: "Source Score",
    category: "Source",
    shortDescription: "Score reflecting the quality, reliability, and completeness of sources used for the asset profile.",
    whyItMatters: "Strong data requires traceable sources, especially for institutional, compliance, and reserve claims.",
    example: "Official issuer docs and regulator filings score higher than aggregators or media mentions",
    valueType: "score",
  },
  completenessScore: {
    label: "Completeness Score",
    category: "Grading",
    shortDescription: "Score measuring how many required fields are populated with verifiable data.",
    whyItMatters: "A complete profile is easier to evaluate, but completeness does not automatically mean low risk.",
    example: "100 means all required fields are filled with acceptable evidence",
    valueType: "score",
  },
  dataQualityGrade: {
    label: "Data Quality Grade",
    category: "Grading",
    shortDescription: "Classification of the asset profile based on evidence depth and review status.",
    whyItMatters: "This separates preliminary research coverage from analytics-ready or institutional-grade data.",
    example: "research, analytics, institutional",
    valueType: "string",
  },
  automationLevel: {
    label: "Automation Level",
    category: "Grading",
    shortDescription: "Indicates whether the profile was AI-assisted, script-generated, or human-reviewed.",
    whyItMatters: "Automation level helps users understand how much manual verification has been applied.",
    example: "ai-assisted, semi-automated, human-reviewed",
    valueType: "string",
  },
  humanReviewed: {
    label: "Human Reviewed",
    category: "Grading",
    shortDescription: "Indicates whether a human reviewer has checked the asset profile.",
    whyItMatters: "Human review is required before treating any profile as institutional-grade.",
    example: "true after manual source verification",
    valueType: "boolean",
  },
  legalReviewed: {
    label: "Legal Reviewed",
    category: "Grading",
    shortDescription: "Indicates whether legal and regulatory fields have been manually reviewed.",
    whyItMatters: "Legal review reduces the risk of overstating regulatory status or investor eligibility.",
    example: "true after prospectus and legal sources are checked",
    valueType: "boolean",
  },
  reserveReviewed: {
    label: "Reserve Reviewed",
    category: "Grading",
    shortDescription: "Indicates whether reserve, backing, custodian, and audit fields have been manually reviewed.",
    whyItMatters: "Reserve review is critical for claims about backing and proof-of-reserves.",
    example: "true after reserve reports and custody disclosures are checked",
    valueType: "boolean",
  },
  sourceReviewed: {
    label: "Source Reviewed",
    category: "Source",
    shortDescription: "Indicates whether the source list and source quality have been manually reviewed.",
    whyItMatters: "Source review helps ensure every claim is traceable to reliable evidence.",
    example: "true when sources.json has been checked",
    valueType: "boolean",
  },
  productionReady: {
    label: "Production Ready",
    category: "Grading",
    shortDescription: "Indicates whether the asset profile is ready for public production use.",
    whyItMatters: "Production readiness separates draft research from published data.",
    example: "false for AI-assisted drafts",
    valueType: "boolean",
  },

  // Source layer
  sources: {
    label: "Sources",
    category: "Source",
    shortDescription: "List of URLs or references supporting the asset profile.",
    whyItMatters: "Sources are the audit trail for every data claim in Nexus RWA.",
    example: "issuer docs, fund reports, explorer URLs, data aggregators",
    valueType: "array",
  },
  sourceType: {
    label: "Source Type",
    category: "Source",
    shortDescription: "Classification of the source used for a field or layer.",
    whyItMatters: "Source type helps separate official evidence from third-party or supporting references.",
    example: "official, regulator, explorer, aggregator, media",
    valueType: "string",
  },
  sourceUrl: {
    label: "Source URL",
    category: "Source",
    shortDescription: "Specific URL supporting a field, value, or claim.",
    whyItMatters: "Field-level source URLs make the dataset auditable and easier to verify.",
    example: "https://issuer.com/docs/reserves",
    valueType: "url",
  },
  reliabilityScore: {
    label: "Reliability Score",
    category: "Source",
    shortDescription: "Score estimating the reliability of a source.",
    whyItMatters: "Reliability scoring helps prioritize official, regulator, and audit sources over weaker references.",
    example: "95 for official fund filing, lower for media article",
    valueType: "score",
  },
  lastChecked: {
    label: "Last Checked",
    category: "Source",
    shortDescription: "Date when a source URL was last manually or automatically checked.",
    whyItMatters: "Source availability can change, so stale links need periodic review.",
    example: "2026-06-04",
    valueType: "date",
  },
  dataGaps: {
    label: "Data Gaps",
    category: "Source",
    shortDescription: "Known missing, unresolved, or unverifiable fields in the asset profile.",
    whyItMatters: "Explicit data gaps improve honesty and prevent weak evidence from being overstated.",
    example: "missing legal opinion URL, no confirmed reserve oracle",
    valueType: "array",
  },
} as const satisfies Record<string, FieldDefinition>;

export type FieldKey = keyof typeof FIELD_DEFINITIONS;

export function getFieldDefinition(fieldKey: string) {
  return FIELD_DEFINITIONS[fieldKey as FieldKey];
}
