"use client";

import { AlertTriangle, Minus, Sparkles, TrendingUp } from "lucide-react";
import { BlurredPreview } from "@/components/paywall/BlurredPreview";
import { PaywallGuard } from "@/components/paywall/PaywallGuard";
import type { ApiResponse, AssetInsight } from "@/lib/shared";

const OUTLOOK_STYLES: Record<
  AssetInsight["outlook"],
  { label: string; className: string; Icon: typeof Minus }
> = {
  bullish: {
    label: "Positive",
    className:
      "border-[rgba(61,154,110,0.4)] bg-[rgba(61,154,110,0.12)] text-[var(--data-positive)]",
    Icon: TrendingUp,
  },
  neutral: {
    label: "Neutral",
    className:
      "border-[var(--border-panel)] bg-[var(--bg-panel)] text-[var(--text-secondary)]",
    Icon: Minus,
  },
  bearish: {
    label: "Cautious",
    className:
      "border-[rgba(196,92,92,0.4)] bg-[rgba(196,92,92,0.12)] text-[var(--data-negative)]",
    Icon: AlertTriangle,
  },
};

function formatHoursAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const hours = Math.max(0, Math.floor(ms / (60 * 60 * 1000)));
  if (hours < 1) return "less than 1 hour ago";
  if (hours === 1) return "1 hour ago";
  return `${hours} hours ago`;
}

function BulletList({
  items,
  dotClassName,
}: {
  items: string[];
  dotClassName: string;
}) {
  return (
    <ul className="space-y-1.5 text-sm text-[var(--text-secondary)]">
      {items.map((item) => (
        <li key={item} className="flex gap-2 leading-snug">
          <span
            className={`mt-2 size-1 shrink-0 rounded-full ${dotClassName}`}
            aria-hidden
          />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

function MockInsightBlurred() {
  return (
    <div className="pointer-events-none select-none space-y-4 blur-[4px]">
      <div className="h-7 w-24 rounded border border-[var(--border-panel)] bg-[var(--bg-panel)]" />
      <p className="text-sm text-[var(--text-secondary)]">
        Treasury-backed structure and stable yield trajectory support a constructive
        near-term view…
      </p>
      <div className="grid gap-4 md:grid-cols-2">
        <ul className="space-y-2 text-sm text-[var(--text-secondary)]">
          <li>Yield above category median</li>
          <li>TVL growth over 30d</li>
        </ul>
        <ul className="space-y-2 text-sm text-[var(--text-secondary)]">
          <li>Concentration risk signal</li>
          <li>Rate sensitivity</li>
        </ul>
      </div>
    </div>
  );
}

function InsightContent({ insight }: { insight: AssetInsight }) {
  const outlook = OUTLOOK_STYLES[insight.outlook];
  const OutlookIcon = outlook.Icon;
  const whatChanged = insight.whatChanged ?? [];
  const watchList = insight.watchList ?? [];

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center gap-3">
        <span
          className={`inline-flex items-center gap-1.5 rounded border px-2 py-0.5 font-mono text-[10px] font-semibold uppercase tracking-wider ${outlook.className}`}
        >
          <OutlookIcon className="size-3" aria-hidden />
          {outlook.label}
        </span>
        <span className="terminal-label">
          Confidence <span className="text-[var(--text-primary)]">{insight.confidence}</span>
        </span>
      </div>

      <p className="text-sm leading-relaxed text-[var(--text-secondary)]">
        {insight.summary}
      </p>

      {whatChanged.length > 0 ? (
        <div>
          <p className="terminal-label mb-2">What changed</p>
          <BulletList items={whatChanged} dotClassName="bg-[var(--accent-amber)]" />
        </div>
      ) : null}

      {watchList.length > 0 ? (
        <div>
          <p className="terminal-label mb-2">Watch</p>
          <BulletList items={watchList} dotClassName="bg-[var(--text-label)]" />
        </div>
      ) : null}

      <div className="grid gap-4 md:grid-cols-2">
        <div className="terminal-panel p-4">
          <h3 className="terminal-label mb-3">Opportunities</h3>
          <BulletList items={insight.opportunities} dotClassName="bg-[var(--data-positive)]" />
        </div>
        <div className="terminal-panel p-4">
          <h3 className="terminal-label mb-3">Risks</h3>
          <BulletList items={insight.risks} dotClassName="bg-[var(--data-negative)]" />
        </div>
      </div>

      <p className="terminal-label border-t border-[var(--border-panel)] pt-3">
        Generated by Claude AI • Updated {formatHoursAgo(insight.generatedAt)}
      </p>
    </div>
  );
}

export type AIInsightCardProps = {
  apiBaseUrl: string;
  assetId: string;
};

export function AIInsightCard({ apiBaseUrl, assetId }: AIInsightCardProps) {
  const base = apiBaseUrl.trim().replace(/\/$/, "");
  const endpoint = `${base}/v1/assets/${assetId}/insight`;

  return (
    <section className="terminal-panel p-6">
      <div className="mb-5 flex items-center gap-3">
        <div
          className="flex size-10 items-center justify-center rounded-lg border border-[var(--border-panel)] bg-[var(--bg-panel)]"
          aria-hidden
        >
          <Sparkles className="size-5 text-[var(--accent-amber)]" />
        </div>
        <div>
          <h2 className="text-lg font-bold text-white">Asset insight</h2>
          <p className="text-sm text-[var(--text-secondary)]">
            Narrative outlook, shifts, and factors to monitor
          </p>
        </div>
      </div>

      <PaywallGuard
        endpoint={endpoint}
        fallback={({ openPaywall }) => (
          <div className="space-y-4">
            <MockInsightBlurred />
            <BlurredPreview
              title="Asset insight"
              priceLabel="Pro — $0.001 ETH"
              onUnlock={openPaywall}
            />
          </div>
        )}
      >
        {(payload) => {
          const body = payload as ApiResponse<AssetInsight>;
          if (
            !body ||
            typeof body !== "object" ||
            !("success" in body) ||
            !body.success
          ) {
            return (
              <p className="text-sm text-[var(--text-secondary)]">
                Insight unavailable, try again later
              </p>
            );
          }
          return <InsightContent insight={body.data} />;
        }}
      </PaywallGuard>
    </section>
  );
}
