"use client";

import { Sparkles, TrendingDown, TrendingUp, Minus } from "lucide-react";
import { BlurredPreview } from "@/components/paywall/BlurredPreview";
import { PaywallGuard } from "@/components/paywall/PaywallGuard";
import type { ApiResponse, AssetInsight } from "@/lib/shared";

const OUTLOOK_STYLES: Record<
  AssetInsight["outlook"],
  { label: string; emoji: string; className: string }
> = {
  bullish: {
    label: "Bullish",
    emoji: "📈",
    className: "border-[rgba(0,255,136,0.35)] bg-[rgba(0,255,136,0.1)] text-[#00FF88]",
  },
  neutral: {
    label: "Neutral",
    emoji: "➖",
    className: "border-[rgba(255,184,0,0.35)] bg-[rgba(255,184,0,0.1)] text-[#FFB800]",
  },
  bearish: {
    label: "Bearish",
    emoji: "📉",
    className: "border-[rgba(255,68,68,0.35)] bg-[rgba(255,68,68,0.1)] text-[#FF8888]",
  },
};

function formatHoursAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const hours = Math.max(0, Math.floor(ms / (60 * 60 * 1000)));
  if (hours < 1) return "less than 1 hour ago";
  if (hours === 1) return "1 hour ago";
  return `${hours} hours ago`;
}

function MockInsightBlurred() {
  return (
    <div className="pointer-events-none select-none space-y-4 blur-[6px]">
      <div className="h-8 w-28 rounded-full bg-[rgba(0,255,136,0.2)]" />
      <p className="text-sm text-[#8892A4]">
        Strong treasury backing and stable yield trajectory support a constructive view
        on near-term performance…
      </p>
      <div className="grid gap-4 md:grid-cols-2">
        <ul className="space-y-2 text-sm text-[#00FF88]">
          <li>Yield above category median</li>
          <li>TVL growth over 30d</li>
        </ul>
        <ul className="space-y-2 text-sm text-[#FF8888]">
          <li>Concentration risk signal</li>
          <li>Rate sensitivity</li>
        </ul>
      </div>
    </div>
  );
}

function InsightContent({ insight }: { insight: AssetInsight }) {
  const outlook = OUTLOOK_STYLES[insight.outlook];
  const OutlookIcon =
    insight.outlook === "bullish"
      ? TrendingUp
      : insight.outlook === "bearish"
        ? TrendingDown
        : Minus;

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-3">
        <span
          className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-sm font-semibold ${outlook.className}`}
        >
          <span aria-hidden>{outlook.emoji}</span>
          <OutlookIcon className="size-4" aria-hidden />
          {outlook.label}
        </span>
        <span className="text-xs uppercase tracking-wide text-[#8892A4]">
          Confidence:{" "}
          <span className="font-medium text-white">{insight.confidence}</span>
        </span>
      </div>

      <p className="text-sm leading-relaxed text-[#C5CED9]">{insight.summary}</p>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="rounded-lg border border-[rgba(0,255,136,0.2)] bg-[rgba(0,255,136,0.04)] p-4">
          <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-[#00FF88]">
            Opportunities
          </h3>
          <ul className="space-y-2 text-sm text-[#C5CED9]">
            {insight.opportunities.map((item) => (
              <li key={item} className="flex gap-2">
                <span className="text-[#00FF88]" aria-hidden>
                  •
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded-lg border border-[rgba(255,68,68,0.2)] bg-[rgba(255,68,68,0.04)] p-4">
          <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-[#FF8888]">
            Risks
          </h3>
          <ul className="space-y-2 text-sm text-[#C5CED9]">
            {insight.risks.map((item) => (
              <li key={item} className="flex gap-2">
                <span className="text-[#FF8888]" aria-hidden>
                  •
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <p className="text-xs text-[#8892A4]">
        Generated by Claude AI • Updated {formatHoursAgo(insight.generatedAt)}
      </p>
    </div>
  );
}

export type AIInsightCardProps = {
  apiBaseUrl: string;
  assetId: string;
};

export function AIInsightCard({ apiBaseUrl, assetId }: AIInsightCardProps) {
  const base = apiBaseUrl.trim().replace(/\/$/, "");
  const endpoint = `${base}/v1/assets/${assetId}/insight`;

  return (
    <section
      className="rounded-xl border border-[rgba(30,42,58,0.8)] p-6"
      style={{ background: "rgba(15,22,41,0.65)" }}
    >
      <div className="mb-5 flex items-center gap-3">
        <div
          className="flex size-10 items-center justify-center rounded-lg border border-[rgba(168,85,247,0.35)] bg-[rgba(168,85,247,0.1)]"
          aria-hidden
        >
          <Sparkles className="size-5 text-[#C084FC]" />
        </div>
        <div>
          <h2 className="text-lg font-bold text-white">AI Insight</h2>
          <p className="text-sm text-[#8892A4]">
            Claude-powered outlook, opportunities, and risks
          </p>
        </div>
      </div>

      <PaywallGuard
        endpoint={endpoint}
        fallback={({ openPaywall }) => (
          <div className="relative">
            <MockInsightBlurred />
            <div className="pointer-events-auto absolute inset-0 flex items-center justify-center p-4">
              <BlurredPreview
                title="AI Insight"
                priceLabel="Pro — $0.001 ETH"
                onUnlock={openPaywall}
                className="max-w-md border-0 bg-transparent"
              />
            </div>
          </div>
        )}
      >
        {(payload) => {
          const body = payload as ApiResponse<AssetInsight>;
          if (
            !body ||
            typeof body !== "object" ||
            !("success" in body) ||
            !body.success
          ) {
            return (
              <p className="text-sm text-[#8892A4]">
                Insight unavailable, try again later
              </p>
            );
          }
          return <InsightContent insight={body.data} />;
        }}
      </PaywallGuard>
    </section>
  );
}
